{"uuid": "c76c6515-0bc6-4899-af74-62812da72a3d", "children": ["4252ae2d-257f-4a1c-ab03-1e1245a5dccc", "e669cb1e-fdf5-4b95-892f-9c985adc778c", "84f3ca85-23e2-4061-a432-c164dca4d3fc"], "befores": [{"name": "all_case_fixture", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidArgumentException: Message: invalid argument\n  (Session info: MicrosoftEdge=140.0.3485.81)\nStacktrace:\n\tGetHandleVerifier [0x0x7ff733cd3f15+18309]\n\t(No symbol) [0x0x7ff733c415c0]\n\t(No symbol) [0x0x7ff733a40df0]\n\t(No symbol) [0x0x7ff733a31402]\n\t(No symbol) [0x0x7ff733a2fd88]\n\t(No symbol) [0x0x7ff733a3031c]\n\t(No symbol) [0x0x7ff733a4464a]\n\t(No symbol) [0x0x7ff733acd5de]\n\t(No symbol) [0x0x7ff733aafc7a]\n\t(No symbol) [0x0x7ff733a8443b]\n\t(No symbol) [0x0x7ff733acd082]\n\t(No symbol) [0x0x7ff733aaf943]\n\t(No symbol) [0x0x7ff733a838e6]\n\t(No symbol) [0x0x7ff733a82b52]\n\t(No symbol) [0x0x7ff733a83723]\n\t(No symbol) [0x0x7ff733b72f75]\n\t(No symbol) [0x0x7ff733b7e74d]\n\tGetHandleVerifier [0x0x7ff733d69603+630387]\n\tGetHandleVerifier [0x0x7ff733d711a1+662033]\n\t(No symbol) [0x0x7ff733c4d6a9]\n\t(No symbol) [0x0x7ff733c47044]\n\t(No symbol) [0x0x7ff733c47193]\n\t(No symbol) [0x0x7ff733c3b016]\n\tBaseThreadInitThunk [0x0x7fffaadae8d7+23]\n\tRtlUserThreadStart [0x0x7fffacd68d9c+44]\n\n", "trace": "  File \"C:\\Users\\31646\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"C:\\Users\\31646\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"C:\\Users\\31646\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\31646\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\31646\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\31646\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 922, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\31646\\AppData\\Local\\Programs\\Python\\venv\\work\\conftest.py\", line 30, in all_case_fixture\n    driver = driver_login_cd()\n             ^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\31646\\AppData\\Local\\Programs\\Python\\venv\\work\\conftest.py\", line 91, in driver_login_cd\n    driver.get(url)\n  File \"C:\\Users\\31646\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 472, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"C:\\Users\\31646\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 447, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\31646\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1760459051022, "stop": 1760459052395}], "start": 1760459051022, "stop": 1760459052645}